export const CATIGORYLIST_FETCH_START = 'CATIGORYLIST_FETCH_START';
export const CATIGORYLIST_FETCH_SUCCESS = 'CATIGORYLIST_FETCH_SUCCESS';
export const CATIGORYLIST_FETCH_ERROR = 'CATIGORYLIST_FETCH_ERROR';

export const CATIGORY_FETCH_START = 'CATIGORY_FETCH_START';
export const CATIGORY_FETCH_SUCCESS = 'CATIGORY_FETCH_SUCCESS';
export const CATIGORY_FETCH_FAIL = 'CATIGORY_FETCH_FAIL';

export const DELETE_CATIGORY_START = 'DELETE_CATIGORY_START';
export const DELETE_CATIGORY_SUCCESS = 'DELETE_CATIGORY_SUCCESS';
export const DELETE_CATIGORY_FAIL = 'DELETE_CATIGORY_FAIL';
export const DELETE_CATIGORY_RESET = 'DELETE_CATIGORY_RESET';

export const CREATE_CATIGORY_START = 'CREATE_CATIGORY_START';
export const CREATE_CATIGORY_SUCCESS = 'CREATE_CATIGORY_SUCCESS';
export const CREATE_CATIGORY_FAIL = 'CREATE_CATIGORY_FAIL';
export const CREATE_CATIGORY_RESET = 'CREATE_CATIGORY_RESET';

export const EDIT_CATIGORY_START = 'EDIT_CATIGORY_START';
export const EDIT_CATIGORY_SUCCESS = 'EDIT_CATIGORY_SUCCESS';
export const EDIT_CATIGORY_FAIL = 'EDIT_CATIGORY_FAIL';
export const EDIT_CATIGORY_RESET = 'EDIT_CATIGORY_RESET';
